# Generated by Django 5.1.6 on 2025-03-03 19:52

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='nombre')),
                ('tiempo', models.CharField(max_length=100, null=True)),
                ('foto', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
            },
        ),
    ]
