# Generated by Django 5.1.6 on 2025-03-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
