# Generated by Django 5.1.6 on 2025-03-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_recetas_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='foto',
            new_name='imagen',
        ),
    ]
