# Generated by Django 5.1.6 on 2025-03-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_rename_foto_recetas_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='imagen',
            new_name='foto',
        ),
    ]
