# Generated by Django 5.1.6 on 2025-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
